Add error if not configured

diff --git a/pureshell b/pureshell
--- a/pureshell
+++ b/pureshell
@@ -1,4 +1,8 @@
 #!/bin/sh
+if [[ -z "PURESHELL_ROOT" ]]; then
+    echo -e "Error: Please configure PureShell."
+	exit 0
+fi
 
 pureshell_install () {
 
@@ -6,12 +10,12 @@ pureshell_install () {
 	PACKAGE=$1
 
 	# Install package
-	if ! rpm -qa | grep -qw $PACKAGE; then
+	# if ! rpm -qa | grep -qw $PACKAGE; then
 		echo -e "\n--- Install ${PACKAGE} ---\n"
-		. "${PURESHELL_ROOT}{PURESHELL_OS}/${PACKAGE}".sh
-	else
-		echo -e "\n--- ${PACKAGE} already installed ---\n"
-	fi
+		. "${PURESHELL_ROOT}${PURESHELL_PLATFORM}/${PACKAGE}".sh
+	# else
+	# 	echo -e "\n--- ${PACKAGE} already installed ---\n"
+	# fi
 }
 
 pureshell_install $1
